In [1]:
import torch
import torch.nn.functional as F

In [2]:
# Construct a 6x6 tensor: first 3 columns [0:3] filled with 1s, last 3 columns [3:6] filled with 0s
input_tensor = torch.tensor([
    [1, 1, 1, 0, 0, 0],
    [1, 1, 1, 0, 0, 0],
    [1, 1, 1, 0, 0, 0],
    [1, 1, 1, 0, 0, 0],
    [1, 1, 1, 0, 0, 0],
    [1, 1, 1, 0, 0, 0]
], dtype=torch.float32).unsqueeze(0).unsqueeze(0)  # Add batch and channel dimensions

print("Input Tensor:")
print(input_tensor)

Input Tensor:
tensor([[[[1., 1., 1., 0., 0., 0.],
          [1., 1., 1., 0., 0., 0.],
          [1., 1., 1., 0., 0., 0.],
          [1., 1., 1., 0., 0., 0.],
          [1., 1., 1., 0., 0., 0.],
          [1., 1., 1., 0., 0., 0.]]]])


In [3]:
# Define a 3x3 kernel tensor for detecting vertical edges
kernel = torch.tensor([
    [-1, 0, 1],
    [-1, 0, 1],
    [-1, 0, 1]
], dtype=torch.float32).unsqueeze(0).unsqueeze(0)  # Add channel and batch dimensions

print("\nKernel Tensor:")
print(kernel)


Kernel Tensor:
tensor([[[[-1.,  0.,  1.],
          [-1.,  0.,  1.],
          [-1.,  0.,  1.]]]])


In [4]:
#  Convolve with Strides
def convolve_with_stride(input_tensor, kernel, stride):
    # Perform convolution using F.conv2d
    output = F.conv2d(input_tensor, kernel, stride=stride, padding=0)
    return output

In [5]:
# Perform convolution with different strides
stride_1 = convolve_with_stride(input_tensor, kernel, stride=1)
stride_2 = convolve_with_stride(input_tensor, kernel, stride=2)

print("\nOutput with Stride = 1:")
print(stride_1)

print("\nOutput with Stride = 2:")
print(stride_2)


Output with Stride = 1:
tensor([[[[ 0., -3., -3.,  0.],
          [ 0., -3., -3.,  0.],
          [ 0., -3., -3.,  0.],
          [ 0., -3., -3.,  0.]]]])

Output with Stride = 2:
tensor([[[[ 0., -3.],
          [ 0., -3.]]]])


In [6]:
# Analyzing the output Output
print("\nAnalysis:")
print("1. With Stride = 1: The output is dense, capturing all vertical edge changes.")
print("2. With Stride = 2: The output is sparse, as the kernel skips positions, reducing spatial resolution.")


Analysis:
1. With Stride = 1: The output is dense, capturing all vertical edge changes.
2. With Stride = 2: The output is sparse, as the kernel skips positions, reducing spatial resolution.


In [ ]:
#Tips and Best Practices
#Padding:
#Add padding to retain the original image dimensions if required:
#python
#F.conv2d(input_tensor, kernel, stride=1, padding=1)